### ISSUE TITLE
error on npm install

### ISSUE THREAD

**Issue by alexucgit** [jpoles1/berrymed-pulseox#1]
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --scripts-prepend-node-path=auto
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code 1
npm ERR! path /Users/stefanoperrino/Desktop/berrymed-pulseox-master/node_modules/node-bluetooth
npm ERR! command failed
npm ERR! command sh -c node-gyp configure build
npm ERR! CXX(target) Release/obj.target/BluetoothSerialPort/src/osx/DeviceINQ.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.2.0
npm ERR! gyp info using node@14.18.1 | darwin | x64
npm ERR! gyp info find Python using Python version 3.10.0 found at "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3"
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/stefanoperrino/Desktop/berrymed-pulseox-master/node_modules/node-bluetooth/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/stefanoperrino/Library/Caches/node-gyp/14.18.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/stefanoperrino/Desktop/berrymed-pulseox-master/node_modules/node-bluetooth',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/osx/DeviceINQ.mm:14:
npm ERR! In file included from ../../nan/nan.h:2884:
npm ERR! ../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
npm ERR!       data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
npm ERR!                                           ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:5272:3: note: 'GetContents' has been explicitly marked deprecated here
npm ERR!   V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
npm ERR!   ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8config.h:402:39: note: expanded from macro 'V8_DEPRECATE_SOON'
npm ERR! # define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
npm ERR!                                       ^
npm ERR! ../src/osx/DeviceINQ.mm:75:16: warning: 'Call' is deprecated [-Wdeprecated-declarations]
npm ERR!         found->Call(2, argv);
npm ERR!                ^
npm ERR! ../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
npm ERR!   NAN_DEPRECATED inline v8::Local<v8::Value>
npm ERR!   ^
npm ERR! ../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
npm ERR! # define NAN_DEPRECATED __attribute__((deprecated))
npm ERR!                                        ^
npm ERR! ../src/osx/DeviceINQ.mm:78:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
npm ERR!     callback->Call(0, 0);
npm ERR!               ^
npm ERR! ../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
npm ERR!   NAN_DEPRECATED inline v8::Local<v8::Value>
npm ERR!   ^
npm ERR! ../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
npm ERR! # define NAN_DEPRECATED __attribute__((deprecated))
npm ERR!                                        ^
npm ERR! ../src/osx/DeviceINQ.mm:109:16: warning: 'Call' is deprecated [-Wdeprecated-declarations]
npm ERR!     baton->cb->Call(1, argv);
npm ERR!                ^
npm ERR! ../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
npm ERR!   NAN_DEPRECATED inline v8::Local<v8::Value>
npm ERR!   ^
npm ERR! ../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
npm ERR! # define NAN_DEPRECATED __attribute__((deprecated))
npm ERR!                                        ^
npm ERR! ../src/osx/DeviceINQ.mm:121:28: error: expected ')'
npm ERR! void DeviceINQ::Init(Handle<Object> target) {
npm ERR!                            ^
npm ERR! ../src/osx/DeviceINQ.mm:121:21: note: to match this '('
npm ERR! void DeviceINQ::Init(Handle<Object> target) {
npm ERR!                     ^
npm ERR! ../src/osx/DeviceINQ.mm:121:17: error: out-of-line definition of 'Init' does not match any declaration in 'DeviceINQ'
npm ERR! void DeviceINQ::Init(Handle<Object> target) {
npm ERR!                 ^~~~
npm ERR! ../src/osx/DeviceINQ.mm:133:5: error: use of undeclared identifier 'target'
npm ERR!     target->Set(Nan::New("DeviceINQ").ToLocalChecked(), t->GetFunction());
npm ERR!     ^
npm ERR! ../src/osx/DeviceINQ.mm:133:72: error: too few arguments to function call, single argument 'context' was not specified
npm ERR!     target->Set(Nan::New("DeviceINQ").ToLocalChecked(), t->GetFunction());
npm ERR!                                                         ~~~~~~~~~~~~~~ ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:6482:46: note: 'GetFunction' declared here
npm ERR!   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
npm ERR!                                              ^
npm ERR! ../src/osx/DeviceINQ.mm:134:5: error: use of undeclared identifier 'target'
npm ERR!     target->Set(Nan::New("DeviceINQ").ToLocalChecked(), t->GetFunction());
npm ERR!     ^
npm ERR! ../src/osx/DeviceINQ.mm:134:72: error: too few arguments to function call, single argument 'context' was not specified
npm ERR!     target->Set(Nan::New("DeviceINQ").ToLocalChecked(), t->GetFunction());
npm ERR!                                                         ~~~~~~~~~~~~~~ ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:6482:46: note: 'GetFunction' declared here
npm ERR!   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
npm ERR!                                              ^
npm ERR! ../src/osx/DeviceINQ.mm:135:5: error: use of undeclared identifier 'target'
npm ERR!     target->Set(Nan::New("DeviceINQ").ToLocalChecked(), t->GetFunction());
npm ERR!     ^
npm ERR! ../src/osx/DeviceINQ.mm:135:72: error: too few arguments to function call, single argument 'context' was not specified
npm ERR!     target->Set(Nan::New("DeviceINQ").ToLocalChecked(), t->GetFunction());
npm ERR!                                                         ~~~~~~~~~~~~~~ ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:6482:46: note: 'GetFunction' declared here
npm ERR!   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
npm ERR!                                              ^
npm ERR! ../src/osx/DeviceINQ.mm:136:5: error: use of undeclared identifier 'target'
npm ERR!     target->Set(Nan::New("DeviceINQ").ToLocalChecked(), t->GetFunction());
npm ERR!     ^
npm ERR! ../src/osx/DeviceINQ.mm:136:72: error: too few arguments to function call, single argument 'context' was not specified
npm ERR!     target->Set(Nan::New("DeviceINQ").ToLocalChecked(), t->GetFunction());
npm ERR!                                                         ~~~~~~~~~~~~~~ ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:6482:46: note: 'GetFunction' declared here
npm ERR!   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
npm ERR!                                              ^
npm ERR! ../src/osx/DeviceINQ.mm:228:16: warning: 'Call' is deprecated [-Wdeprecated-declarations]
npm ERR!         found->Call(2, argv);
npm ERR!                ^
npm ERR! ../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
npm ERR!   NAN_DEPRECATED inline v8::Local<v8::Value>
npm ERR!   ^
npm ERR! ../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
npm ERR! # define NAN_DEPRECATED __attribute__((deprecated))
npm ERR!                                        ^
npm ERR! ../src/osx/DeviceINQ.mm:231:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
npm ERR!     callback->Call(0, 0);
npm ERR!               ^
npm ERR! ../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
npm ERR!   NAN_DEPRECATED inline v8::Local<v8::Value>
npm ERR!   ^
npm ERR! ../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
npm ERR! # define NAN_DEPRECATED __attribute__((deprecated))
npm ERR!                                        ^
npm ERR! ../src/osx/DeviceINQ.mm:246:23: error: no matching constructor for initialization of 'String::Utf8Value'
npm ERR!     String::Utf8Value address(info[0]);
npm ERR!                       ^       ~~~~~~~
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3294:5: note: candidate constructor not viable: no known conversion from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st argument
npm ERR!     Utf8Value(const Utf8Value&) = delete;
npm ERR!     ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3287:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
npm ERR!     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
npm ERR!     ^
npm ERR! ../src/osx/DeviceINQ.mm:297:20: error: no matching member function for call to 'Set'
npm ERR!         deviceObj->Set(Nan::New("name").ToLocalChecked(), Nan::New([device.nameOrAddress UTF8String]).ToLocalChecked());
npm ERR!         ~~~~~~~~~~~^~~
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR!                                     ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
npm ERR!                                     ^
npm ERR! ../src/osx/DeviceINQ.mm:298:20: error: no matching member function for call to 'Set'
npm ERR!         deviceObj->Set(Nan::New("address").ToLocalChecked(), Nan::New([device.addressString UTF8String]).ToLocalChecked());
npm ERR!         ~~~~~~~~~~~^~~
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR!                                     ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
npm ERR!                                     ^
npm ERR! ../src/osx/DeviceINQ.mm:308:25: error: no matching member function for call to 'Set'
npm ERR!             serviceObj->Set(Nan::New("channel").ToLocalChecked(), Nan::New((int)channelID));
npm ERR!             ~~~~~~~~~~~~^~~
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR!                                     ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
npm ERR!                                     ^
npm ERR! ../src/osx/DeviceINQ.mm:311:29: error: no matching member function for call to 'Set'
npm ERR!                 serviceObj->Set(Nan::New("name").ToLocalChecked(), Nan::New([[service getServiceName] UTF8String]).ToLocalChecked());
npm ERR!                 ~~~~~~~~~~~~^~~
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR!                                     ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
npm ERR!                                     ^
npm ERR! ../src/osx/DeviceINQ.mm:313:29: error: no matching member function for call to 'Set'
npm ERR!                 serviceObj->Set(Nan::New("name").ToLocalChecked(), Nan::Undefined());
npm ERR!                 ~~~~~~~~~~~~^~~
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR!                                     ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
npm ERR!                                     ^
npm ERR! ../src/osx/DeviceINQ.mm:315:28: error: no matching member function for call to 'Set'
npm ERR!             servicesArray->Set(j, serviceObj);
npm ERR!             ~~~~~~~~~~~~~~~^~~
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR!                                     ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
npm ERR!                                     ^
npm ERR! ../src/osx/DeviceINQ.mm:317:20: error: no matching member function for call to 'Set'
npm ERR!         deviceObj->Set(Nan::New("services").ToLocalChecked(), servicesArray);
npm ERR!         ~~~~~~~~~~~^~~
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR!                                     ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
npm ERR!                                     ^
npm ERR! ../src/osx/DeviceINQ.mm:319:22: error: no matching member function for call to 'Set'
npm ERR!         resultArray->Set(i, deviceObj);
npm ERR!         ~~~~~~~~~~~~~^~~
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
npm ERR!                                     ^
npm ERR! /Users/stefanoperrino/Library/Caches/node-gyp/14.18.1/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
npm ERR!   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
npm ERR!                                     ^
npm ERR! fatal error: too many errors emitted, stopping now [-ferror-limit=]
npm ERR! 6 warnings and 20 errors generated.
npm ERR! make: *** [Release/obj.target/BluetoothSerialPort/src/osx/DeviceINQ.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
npm ERR! gyp ERR! System Darwin 21.1.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
npm ERR! gyp ERR! cwd /Users/stefanoperrino/Desktop/berrymed-pulseox-master/node_modules/node-bluetooth
npm ERR! gyp ERR! node -v v14.18.1
npm ERR! gyp ERR! node-gyp -v v8.2.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stefanoperrino/.npm/_logs/2021-12-09T21_05_12_344Z-debug.log

Process finished with exit code 1

**Comment by alexucgit** [comment]
my npm version is 8.1.0
